name: "Terraform Plan - Test"

on:
  push:
    branches:
      - test

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_EMAIL: ${{ vars.TF_EMAIL }}
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE_TEST }}
  CONFIG_DIRECTORY: "./builders/"
  EMAILS_DIRECTORY: "./builders/emails/"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.4
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: true

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.4
        id: plan-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.4
        id: plan-output
        with:
          plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}

      - name: Compose email
        run: ./emailcomposer.sh ${{ steps.plan-output.outputs.add }} ${{ steps.plan-output.outputs.change }} ${{ steps.plan-output.outputs.destroy }} ${{ steps.plan-run.outputs.run_link }}
        working-directory: ${{ env.EMAILS_DIRECTORY }}

      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional (recommended) mail server username:
          username: ${{ secrets.MAIL_USERNAME }}
          # Optional (recommended) mail server password:
          password: ${{ secrets.MAIL_PASSWORD }}
          # Required mail subject:
          subject: "Terraform Cloud Plan - ${{ github.ref_name }} (${{ steps.vars.outputs.sha_short }})" 
          # Required recipients' addresses:
          to: ${{ env.TF_EMAIL }}
          # Required sender full name (address can be skipped):
          from: Terraform planner
          # Optional HTML body read from file:
          html_body: file://builders/emails/tfcplanoutput.html
