name: Build and configure Terraform Cloud (TFC)

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        environment: testenvironment

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Docker image
              run: docker build . --tag tfcbuilder
              working-directory: tfcbuilder

            - name: Run Docker container
              run: docker run --env-file=".env.tfcbuilder" tfcbuilder
              working-directory: tfcbuilder
              env:
                TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
                TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
                TF_EMAIL: ${{ vars.TF_EMAIL }}
                TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
